RANDOM_SEED = None
START_LIVES = 3

# TIME
SAFE_SPAWN_TIME = 2.0  # Invulnerabilidade
WAVE_DELAY = 2.0
UFO_SPAWN_EVERY = 15.0
UFO_FIRE_EVERY = 1.2
SHIP_FIRE_RATE = 0.2

MAX_BULLETS = 4
HYPERSPACE_COST = 250
